# Generated by Django 4.2.29 on 2026-03-19 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='简历标题')),
                ('resume_data', models.JSONField(default=dict, verbose_name='简历数据')),
                ('pdf_file', models.FileField(blank=True, upload_to='pdfs/', verbose_name='PDF文件')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('failed', '生成失败')], default='draft', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='templates.resumetemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'db_table': 'resumes_resume',
                'ordering': ['-created_at'],
            },
        ),
    ]
