# Generated by Django 4.2.29 on 2026-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='share_count',
            field=models.IntegerField(default=0, verbose_name='分享次数'),
        ),
        migrations.AddField(
            model_name='resume',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='分享令牌'),
        ),
        migrations.AddField(
            model_name='resume',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
