# Generated by Django 4.2.30 on 2026-04-21 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resume_share_count_resume_share_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="share_token",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True
            ),
        ),
    ]
