"""
Export the current MySQL database schema and data to a single SQL file.
"""

from __future__ import annotations

import os
from pathlib import Path

import django


BASE_DIR = Path(__file__).resolve().parent
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "resume_project.settings")
django.setup()

from django.conf import settings  # noqa: E402
from django.db import connection  # noqa: E402


OUTPUT_FILE = BASE_DIR / "resume_generator.sql"


def sql_literal(value):
    raw = connection.connection.literal(value)
    if isinstance(raw, bytes):
        return raw.decode("utf-8")
    return str(raw)


def fetch_tables(cursor):
    cursor.execute("SHOW TABLES")
    return [row[0] for row in cursor.fetchall()]


def fetch_create_table(cursor, table_name):
    cursor.execute(f"SHOW CREATE TABLE `{table_name}`")
    return cursor.fetchone()[1]


def fetch_rows(cursor, table_name):
    cursor.execute(f"SELECT * FROM `{table_name}`")
    columns = [description[0] for description in cursor.description]
    rows = cursor.fetchall()
    return columns, rows


def main():
    connection.ensure_connection()
    database_name = settings.DATABASES["default"]["NAME"]

    with connection.cursor() as cursor:
        tables = fetch_tables(cursor)

        output = [
            "-- Resume Generator database export",
            "-- Generated by backend/export_sql.py",
            "SET NAMES utf8mb4;",
            "SET FOREIGN_KEY_CHECKS = 0;",
            f"CREATE DATABASE IF NOT EXISTS `{database_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            f"USE `{database_name}`;",
            "",
        ]

        for table_name in tables:
            create_sql = fetch_create_table(cursor, table_name)
            output.append(f"-- Table structure for `{table_name}`")
            output.append(f"DROP TABLE IF EXISTS `{table_name}`;")
            output.append(f"{create_sql};")
            output.append("")

        for table_name in tables:
            columns, rows = fetch_rows(cursor, table_name)
            output.append(f"-- Data for `{table_name}`")

            if rows:
                column_sql = ", ".join(f"`{column}`" for column in columns)
                for row in rows:
                    values_sql = ", ".join(sql_literal(value) for value in row)
                    output.append(
                        f"INSERT INTO `{table_name}` ({column_sql}) VALUES ({values_sql});"
                    )
            else:
                output.append(f"-- `{table_name}` has no rows")

            output.append("")

        output.append("SET FOREIGN_KEY_CHECKS = 1;")
        output.append("")

    OUTPUT_FILE.write_text("\n".join(output), encoding="utf-8")
    print(f"Exported SQL to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
