# Generated by Django 4.2.29 on 2026-03-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('thumbnail', models.ImageField(blank=True, upload_to='templates/thumbnails/', verbose_name='缩略图')),
                ('html_content', models.TextField(verbose_name='HTML模板内容')),
                ('css_content', models.TextField(blank=True, verbose_name='CSS样式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '简历模板',
                'verbose_name_plural': '简历模板',
                'db_table': 'templates_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
