# Generated by Django 4.2.29 on 2026-04-01 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='category',
            field=models.CharField(choices=[('classic', '经典'), ('modern', '现代'), ('creative', '创意'), ('simple', '简约'), ('colorful', '多彩')], default='classic', max_length=20, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='color_scheme',
            field=models.JSONField(default=dict, verbose_name='配色方案'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='是否自定义'),
        ),
    ]
